### ISSUE TITLE
LocalStorage HTML5 (use instead of a db)

### ISSUE THREAD

**Issue by selinaross** [WebDevBootcamp/archiVe#20]
http://diveintohtml5.info/storage.html
http://www.smashingmagazine.com/2010/10/11/local-storage-and-how-to-use-it/

**Comment by selinaross** [comment]
I can do this since it is directly related to the drop event. E.g. when a book/tile (search results) is dropped into one of the four categories/collections it will need to be stored in local storage. I can also handle the event that displays the stored books/tiles (the stored results will need to be retrieved from local storage to be displayed). 

Does this make sense? Let me know if I'm missing something regarding this process.

**Comment by ysjoyce** [comment]
We need a step by step (frame by frame) outline so that we are all on the same page and not duplicating code.  I will add this process to the ReadMe today. We do need a place to store the collections. Since Patrick is setting up the search frame, coordinate with him who is setting up the collations frame so that it looks similar to the search frame (same theme).
Is that what you meant, or did you mean setting up the database structure?

**Comment by selinaross** [comment]
Yeah, I meant that I'll be setting up the database structure.

**Comment by selinaross** [comment]
I agree it would be helpful to have a step by step outline - thanks for doing that!

**Comment by patrickmulcrone** [comment]
@ysjoyce Can you please merge your code to this repo?

**Comment by ysjoyce** [comment]
Please check to see if I have indeed merged my files and let me know.

**Comment by patrickmulcrone** [comment]
Yes, thank you!!!

**Comment by selinaross** [comment]
A quick update:
I've set up local storage which stores "books" in the collections. I'm working on moving a book from one collection to another (in case a user changes their mind), and on displaying the collection of books when a collection is clicked on.
