### ISSUE TITLE
design "bookshelf" wireframe

### ISSUE THREAD

**Issue by dlpeters** [WebDevBootcamp/archiVe#7]
Is this a separate web page or are the search & display functions on  only one page?

**Comment by patrickmulcrone** [comment]
I know we talked about building a page that displays books on a virtual bookshelf using wood grain finish, etc. I can make it on Monday, but...

I am still resistant to the idea because
1. skeuomorphism is considered passe in the design world after Microsoft released Windows 8 and everyone followed suit (incuding Apple) and currently use flat design.
2. It won't match the UI from what has already been created.

Any thoughts?

**Comment by ysjoyce** [comment]
I don't have my heart set on the wood grain. I really don't want out design to be "passé". I'm flexible. Have you seen any alternative designs?

**Comment by selinaross** [comment]
I agree about not using the virtual bookshelf with the wood grain finish. For simplicity, what about using the same grid structure (with the same functionality) that we used for the search page and change the look and feel of the page with css?

**Comment by selinaross** [comment]
We're using the same grid structure for both the search and display collection pages.
